name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    uses: harmonysoft-tech/ci/.github/workflows/library-gradle-release-maven-central.yml@main
    secrets: inherit
    permissions:
      contents: write